<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12091" started-at="2019-03-17T05:09:34Z" finished-at="2019-03-17T05:09:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12091" started-at="2019-03-17T05:09:34Z" finished-at="2019-03-17T05:09:46Z">
      <class name="Tests.LoginTests">
        <test-method status="PASS" signature="setUpEnvironment()[pri:0, instance:Tests.LoginTests@5034c75a]" name="setUpEnvironment" is-config="true" duration-ms="11219" started-at="2019-03-17T05:09:34Z" finished-at="2019-03-17T05:09:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpEnvironment -->
        <test-method status="FAIL" signature="verifyLogin()[pri:0, instance:Tests.LoginTests@5034c75a]" name="verifyLogin" duration-ms="310" started-at="2019-03-17T05:09:46Z" description="Verify Login" finished-at="2019-03-17T05:09:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verify Login expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verify Login expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at Tests.LoginTests.verifyLogin(LoginTests.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="closeEnvironment()[pri:0, instance:Tests.LoginTests@5034c75a]" name="closeEnvironment" is-config="true" duration-ms="500" started-at="2019-03-17T05:09:46Z" finished-at="2019-03-17T05:09:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeEnvironment -->
      </class> <!-- Tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
